CREATE TABLE incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_system TEXT NOT NULL,
    source_record_id TEXT NOT NULL,

    source_offense_code TEXT NOT NULL,
    source_offense_description TEXT NOT NULL,

    family_violence BOOLEAN NOT NULL,

    occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    reported_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    location_type TEXT,

    council_district INTEGER,
    apd_sector TEXT,
    apd_district TEXT,

    clearance_status TEXT,
    clearance_date DATE,

    ucr_category TEXT,
    category_description TEXT,
    census_block_group TEXT,

    imported_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_incidents_source_record
        UNIQUE (source_system, source_record_id),

    CONSTRAINT chk_incidents_council_district
        CHECK (
            council_district IS NULL
            OR council_district BETWEEN 1 AND 10
        ),

    CONSTRAINT chk_incidents_clearance_status
        CHECK (
            clearance_status IS NULL
            OR clearance_status IN (
                'CLEARED_BY_ARREST',
                'CLEARED_BY_EXCEPTION',
                'NOT_CLEARED'
            )
        )
);

CREATE INDEX idx_incidents_occurred_at
    ON incidents (occurred_at);
